#! /usr/bin/env python

sample = {
    'data_obs' : {
        'files' : ['SingleMuon_Run2016B', 'SingleMuon_Run2016C', 'SingleMuon_Run2016D', 'SingleMuon_Run2016E', 'SingleMuon_Run2016F', 'SingleMuon_Run2016G', 'SingleMuon_Run2016H', 'SingleElectron_Run2016B', 'SingleElectron_Run2016C', 'SingleElectron_Run2016D', 'SingleElectron_Run2016E', 'SingleElectron_Run2016F', 'SingleElectron_Run2016G', 'SingleElectron_Run2016H', 'MET_Run2016B', 'MET_Run2016C', 'MET_Run2016D', 'MET_Run2016E', 'MET_Run2016F', 'MET_Run2016G', 'MET_Run2016H', 'JetHT_Run2016B', 'JetHT_Run2016C', 'JetHT_Run2016D', 'JetHT_Run2016E', 'JetHT_Run2016F', 'JetHT_Run2016G', 'JetHT_Run2016H'],
        'fillcolor' : 0,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Data",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL' : {
        'files' : ['DYJetsToLL'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL_HT' : {
        'files' : ['DYJetsToLL_HT-100to200', 'DYJetsToLL_HT-200to400', 'DYJetsToLL_HT-400to600', 'DYJetsToLL_HT-600to800', 'DYJetsToLL_HT-800to1200', 'DYJetsToLL_HT-1200to2500', 'DYJetsToLL_HT-2500toInf'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL_Pt' : {
        'files' : ['DYJetsToLL_Pt-100To250', 'DYJetsToLL_Pt-250To400', 'DYJetsToLL_Pt-400To650', 'DYJetsToLL_Pt-650ToInf'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu' : {
        'files' : ['DYJetsToNuNu'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu_HT' : {
        'files' : ['ZJetsToNuNu_HT-100To200', 'ZJetsToNuNu_HT-200To400', 'ZJetsToNuNu_HT-400To600', 'ZJetsToNuNu_HT-600To800', 'ZJetsToNuNu_HT-800To1200', 'ZJetsToNuNu_HT-1200To2500', 'ZJetsToNuNu_HT-2500ToInf'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu_Pt' : {
        'files' : ['DYJetsToNuNu_Pt-100To250', 'DYJetsToNuNu_Pt-250To400', 'DYJetsToNuNu_Pt-400To650', 'DYJetsToNuNu_Pt-650ToInf'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu' : {
        'files' : ['WJetsToLNu'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu_HT' : {
        'files' : ['WJetsToLNu_HT-70To100', 'WJetsToLNu_HT-100To200', 'WJetsToLNu_HT-200To400', 'WJetsToLNu_HT-400To600', 'WJetsToLNu_HT-600To800', 'WJetsToLNu_HT-800To1200', 'WJetsToLNu_HT-1200To2500', 'WJetsToLNu_HT-2500ToInf', 'WJetsToQQ_HT-600ToInf'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu_Pt' : {
        'files' : ['WJetsToLNu_Pt-100To250', 'WJetsToLNu_Pt-250To400', 'WJetsToLNu_Pt-400To600', 'WJetsToLNu_Pt-600ToInf'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'TTbar' : {
        'files' : ['TT', 'TTWJetsToLNu', 'TTZToLLNuNu','TTZToQQ','TTWJetsToQQ'],
        'fillcolor' : 798,
        'fillstyle' : 1001,
        'linecolor' : 798,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t#bar{t}",#, single t
        'weight': 1.,
        'plot': True,
    }, 
    'TTbarSL' : {
        'files' : ['TTTo2L2Nu', 'TTToSemiLeptonic', 'TTWJetsToLNu', 'TTZToLLNuNu','TTZToQQ','TTWJetsToQQ'],
        'fillcolor' : 798,
        'fillstyle' : 1001,
        'linecolor' : 798,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t#bar{t}",#, single t
        'weight': 1.,
        'plot': True,
    },
    'TTbar2L' : {
      'files' : ['TTTo2L2Nu'],
        'fillcolor' : 798,
        'fillstyle' : 1001,
        'linecolor' : 798,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t#bar{t}(2l)",#, single t
        'weight': 1.,
        'plot': True,
    },
    'TTbar1L' : {
      'files' : ['TTToSemiLeptonic'],
        'fillcolor' : 797,#805
        'fillstyle' : 1001,
        'linecolor' : 797,#805
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t#bar{t}(1l)",#, single t
        'weight': 1.,
        'plot': True,
    },
    'TTbarV' : {
      'files' : ['TTWJetsToLNu', 'TTZToLLNuNu','TTZToQQ','TTWJetsToQQ'],
        'fillcolor' : 804,
        'fillstyle' : 1001,
        'linecolor' : 804,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t#bar{t}+V",#, single t
        'weight': 1.,
        'plot': True,
    },
    'ST' : {
        'files' : ['ST_s-channel', 'ST_t-channel_antitop', 'ST_t-channel_top', 'ST_tW_antitop', 'ST_tW_top'],
        'fillcolor' : 807,#801
        'fillstyle' : 1001,
        'linecolor' : 807,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t+X",
        'weight': 1.,
        'plot': True,
    },
    'VV' : {
        'files' : ['WWTo1L1Nu2Q', 'WWTo2L2Nu', 'WWTo4Q', 'WZTo1L1Nu2Q', 'WZTo2L2Q', 'WZTo2Q2Nu', 'ZZTo2L2Q', 'ZZTo2Q2Nu', 'ZZTo2L2Nu', 'ZZTo4L', 'ZZTo4Q', 'GluGluHToBB', 'WHToLNuBB', 'ZHToLLBB', 'ZHToNuNuBB', 'ZHToQQBB','WZTo1L3Nu','WZTo3LNu'],
        'fillcolor' : 602,
        'fillstyle' : 1001,
        'linecolor' : 602,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "VV, VH",
        'weight': 1.,
        'plot': True,
    },
    'Higgs' : {
        'files' : ['GluGluHToBB', 'WHToLNuBB', 'ZHToLLBB', 'ZHToNuNuBB', 'ZHToQQBB'],
        'fillcolor' : 628,
        'fillstyle' : 1001,
        'linecolor' : 629,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "SM Higgs",
        'weight': 1.,
        'plot': True,
    },
    'QCD' : {
        'files' : ['QCD_HT100to200', 'QCD_HT200to300', 'QCD_HT300to500', 'QCD_HT500to700', 'QCD_HT700to1000', 'QCD_HT1000to1500', 'QCD_HT1500to2000', 'QCD_HT2000toInf'],
        'fillcolor' : 921,
        'fillstyle' : 1001,
        'linecolor' : 921,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "multijet",
        'weight': 1.,
        'plot': True,
    },

    'AllBkg' : {
        'files' : [],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "All backgrounds",
        'weight': 1.,
        'plot': True,
    },
    
        
    # Dummy entry for background sum
    'BkgSum' : {
        'order' : 0,
        'files' : [],
        'fillcolor' : 1,
        'fillstyle' : 3003,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "MC stat.",
        'weight': 1.,
        'plot': True,
    },
    
    'PreFit' : {
        'order' : 0,
        'files' : [],
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 923,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "Pre-fit",
        'weight': 1.,
        'plot': True,
    },
    

################# DM

    'tDM_MChi1_MPhi10_OP' : {
        'order' : 1001,
        'files' : ['TopDMJets_scalar_tChan_Mchi-1_Mphi-10', 'TopDMJets_scalar_tWChan_Mchi-1_Mphi-10'],
        'fillcolor' : 2,
        'fillstyle' : 3005,
        'linecolor' : 2,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t+DM, m_{#phi}=10 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tDM_MChi1_MPhi20_OP' : {
        'order' : 1001,
        'files' : ['TopDMJets_scalar_tChan_Mchi-1_Mphi-20', 'TopDMJets_scalar_tWChan_Mchi-1_Mphi-20'],
        'fillcolor' : 2,
        'fillstyle' : 3005,
        'linecolor' : 2,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t+DM, m_{#phi}=20 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tDM_MChi1_MPhi50_OP' : {
        'order' : 1001,
        'files' : ['TopDMJets_scalar_tChan_Mchi-1_Mphi-50', 'TopDMJets_scalar_tWChan_Mchi-1_Mphi-50'],
        'fillcolor' : 2,
        'fillstyle' : 3005,
        'linecolor' : 2,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t+DM, m_{#phi}=50 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tDM_MChi1_MPhi100_OP' : {
        'order' : 1001,
        'files' : ['TopDMJets_scalar_tChan_Mchi-1_Mphi-100', 'TopDMJets_scalar_tWChan_Mchi-1_Mphi-100'],
        'fillcolor' : 2,
        'fillstyle' : 3005,
        'linecolor' : 2,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t+DM, m_{#phi}=100 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tDM_MChi1_MPhi200_OP' : {
        'order' : 1001,
        'files' : ['TopDMJets_scalar_tChan_Mchi-1_Mphi-200', 'TopDMJets_scalar_tWChan_Mchi-1_Mphi-200'],
        'fillcolor' : 2,
        'fillstyle' : 3005,
        'linecolor' : 2,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t+DM, m_{#phi}=200 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tDM_MChi1_MPhi300_OP' : {
        'order' : 1001,
        'files' : ['TopDMJets_scalar_tChan_Mchi-1_Mphi-300', 'TopDMJets_scalar_tWChan_Mchi-1_Mphi-300'],
        'fillcolor' : 2,
        'fillstyle' : 3005,
        'linecolor' : 2,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t+DM, m_{#phi}=300 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tDM_MChi1_MPhi500_OP' : {
        'order' : 1001,
        'files' : ['TopDMJets_scalar_tChan_Mchi-1_Mphi-500', 'TopDMJets_scalar_tWChan_Mchi-1_Mphi-500'],
        'fillcolor' : 2,
        'fillstyle' : 3005,
        'linecolor' : 2,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t+DM, m_{#phi}=500 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tDM_MChi1_MPhi100' : {
        'order' : 1001,
        'files' : ['DMScalar_top_tChan_MChi1_MPhi100', 'DMScalar_top_tWChan_MChi1_MPhi100'],
        'fillcolor' : 2,#625
        'fillstyle' : 3005,
        'linecolor' : 2,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "#splitline{t+DM,}{m_{#phi}=100 GeV}",
        'weight': 1.,
        'plot': True,
    },

    'tDM_MChi1_MPhi300' : {
        'order' : 1001,
        'files' : ['DMScalar_top_tChan_MChi1_MPhi300', 'DMScalar_top_tWChan_MChi1_MPhi300'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t+DM, m_{#phi}=300 GeV",
        'weight': 1.,
        'plot': True,
    },
    
    'ttDM_MChi1_MPhi10' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-10'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    'ttDM_MChi1_MPhi20' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-20'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=20 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    'ttDM_MChi1_MPhi50' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-50'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    'ttDM_MChi1_MPhi100' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-100'],
        'fillcolor' : 2,
        'fillstyle' : 3005,
        'linecolor' : 2,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "#splitline{tt+DM,}{m_{#phi}=100 GeV}",
        'weight': 1.,
        'plot': True,
    },
    
    'ttDM_MChi1_MPhi200' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-200'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=200 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDM_MChi1_MPhi300' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-300'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=300 GeV",
        'weight': 1.,
        'plot': True,
    },
    
    'ttDM_MChi1_MPhi500' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-500'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    'ttDM_MChi1_MPhi1000' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-1000'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=1000 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    'tttDM_MChi1_MPhi10' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-10', 'TopDMJets_scalar_tChan_Mchi-1_Mphi-10','TopDMJets_scalar_tWChan_Mchi-1_Mphi-10'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t, tt+DM, m_{#phi}=10 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tttDM_MChi1_MPhi20' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-20', 'TopDMJets_scalar_tChan_Mchi-1_Mphi-20','TopDMJets_scalar_tWChan_Mchi-1_Mphi-20'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t, tt+DM, m_{#phi}=20 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tttDM_MChi1_MPhi50' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-50', 'TopDMJets_scalar_tChan_Mchi-1_Mphi-50','TopDMJets_scalar_tWChan_Mchi-1_Mphi-50'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t, tt+DM, m_{#phi}=50 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tttDM_MChi1_MPhi100' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-100', 'TopDMJets_scalar_tChan_Mchi-1_Mphi-100','TopDMJets_scalar_tWChan_Mchi-1_Mphi-100'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t, tt+DM, m_{#phi}=100 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tttDM_MChi1_MPhi200' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-200', 'TopDMJets_scalar_tChan_Mchi-1_Mphi-200','TopDMJets_scalar_tWChan_Mchi-1_Mphi-200'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t, tt+DM, m_{#phi}=200 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tttDM_MChi1_MPhi300' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-300', 'TopDMJets_scalar_tChan_Mchi-1_Mphi-300','TopDMJets_scalar_tWChan_Mchi-1_Mphi-300'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t, tt+DM, m_{#phi}=300 GeV",
        'weight': 1.,
        'plot': True,
    },

    'tttDM_MChi1_MPhi500' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-500', 'TopDMJets_scalar_tChan_Mchi-1_Mphi-500','TopDMJets_scalar_tWChan_Mchi-1_Mphi-500'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t, tt+DM, m_{#phi}=500 GeV",
        'weight': 1.,
        'plot': True,
    },
}

################# Mono-H

for mZ in [800, 1000, 1200, 1400, 1700, 2000, 2500, 2750, 3000, 3500, 4000]:
   for mA in [300, 400, 500, 600, 700, 800]:
       if mZ in [800] and mA in [700, 800]: continue
       if mZ in [2750, 3000, 3500, 4000] and mA in [400, 600, 700]: continue
       sample["monoH_MZ%d_MA%d" % (mZ, mA)] = {'order' : 1001, 'files' : ["ZprimeToA0hToA0chichihbb_2HDM_MZp-%d_MA0-%d" % (mZ, mA)], 'fillcolor' : 636, 'fillstyle' : 3005, 'linecolor' : 636, 'linewidth' : 3, 'linestyle' : 1, 'label' : "m_{Z'} = %d GeV, m_{A} = %d GeV" % (mZ, mA), 'weight': 1., 'plot': False,}

