#! /usr/bin/env python

sample = {
    'data_obs' : {
        'files' : ['SingleMuon_Run2016B', 'SingleMuon_Run2016C', 'SingleMuon_Run2016D', 'SingleMuon_Run2016E', 'SingleMuon_Run2016F', 'SingleMuon_Run2016G', 'SingleMuon_Run2016H', 'SingleElectron_Run2016B', 'SingleElectron_Run2016C', 'SingleElectron_Run2016D', 'SingleElectron_Run2016E', 'SingleElectron_Run2016F', 'SingleElectron_Run2016G', 'SingleElectron_Run2016H', 'MET_Run2016B', 'MET_Run2016C', 'MET_Run2016D', 'MET_Run2016E', 'MET_Run2016F', 'MET_Run2016G', 'MET_Run2016H', 'JetHT_Run2016B', 'JetHT_Run2016C', 'JetHT_Run2016D', 'JetHT_Run2016E', 'JetHT_Run2016F', 'JetHT_Run2016G', 'JetHT_Run2016H'],
#        'files' : ['JetHT_Run2016B', 'JetHT_Run2016C', 'JetHT_Run2016D', 'JetHT_Run2016E', 'JetHT_Run2016F', 'JetHT_Run2016G', 'JetHT_Run2016H'],
        'fillcolor' : 0,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Data",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL' : {
        'files' : ['DYJetsToLL'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL_HT' : {
        'files' : ['DYJetsToLL_HT-100to200', 'DYJetsToLL_HT-200to400', 'DYJetsToLL_HT-400to600', 'DYJetsToLL_HT-600to800', 'DYJetsToLL_HT-800to1200', 'DYJetsToLL_HT-1200to2500', 'DYJetsToLL_HT-2500toInf'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL-0b' : {
        'files' : ['DYJetsToLL', 'DYJetsToLL_HT-100to200', 'DYJetsToLL_HT-200to400', 'DYJetsToLL_HT-400to600', 'DYJetsToLL_HT-600to800', 'DYJetsToLL_HT-800to1200', 'DYJetsToLL_HT-1200to2500', 'DYJetsToLL_HT-2500toInf', 'DY1JetsToLL', 'DY2JetsToLL', 'DY3JetsToLL', 'DY4JetsToLL'],
        'fillcolor' : 410,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL-1b' : {
        'files' : ['DYJetsToLL', 'DYJetsToLL_HT-100to200', 'DYJetsToLL_HT-200to400', 'DYJetsToLL_HT-400to600', 'DYJetsToLL_HT-600to800', 'DYJetsToLL_HT-800to1200', 'DYJetsToLL_HT-1200to2500', 'DYJetsToLL_HT-2500toInf', 'DY1JetsToLL', 'DY2JetsToLL', 'DY3JetsToLL', 'DY4JetsToLL'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 419,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + b",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL-2b' : {
        'files' : ['DYJetsToLL', 'DYJetsToLL_HT-100to200', 'DYJetsToLL_HT-200to400', 'DYJetsToLL_HT-400to600', 'DYJetsToLL_HT-600to800', 'DYJetsToLL_HT-800to1200', 'DYJetsToLL_HT-1200to2500', 'DYJetsToLL_HT-2500toInf', 'DY1JetsToLL', 'DY2JetsToLL', 'DY3JetsToLL', 'DY4JetsToLL'],
        'fillcolor' : 419,
        'fillstyle' : 1001,
        'linecolor' : 420,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + b#bar{b}",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL_Pt' : {
        'files' : ['DYJetsToLL_Pt-100To250', 'DYJetsToLL_Pt-250To400', 'DYJetsToLL_Pt-400To650', 'DYJetsToLL_Pt-650ToInf'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL_Pt-0b' : {
        'files' : ['DYJetsToLL', 'DYJetsToLL_Pt-100To250', 'DYJetsToLL_Pt-250To400', 'DYJetsToLL_Pt-400To650', 'DYJetsToLL_Pt-650ToInf'],
        'fillcolor' : 410,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL_Pt-1b' : {
        'files' : ['DYJetsToLL', 'DYJetsToLL_Pt-100To250', 'DYJetsToLL_Pt-250To400', 'DYJetsToLL_Pt-400To650', 'DYJetsToLL_Pt-650ToInf'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 419,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + b",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL_Pt-2b' : {
        'files' : ['DYJetsToLL', 'DYJetsToLL_Pt-100To250', 'DYJetsToLL_Pt-250To400', 'DYJetsToLL_Pt-400To650', 'DYJetsToLL_Pt-650ToInf'],
        'fillcolor' : 419,
        'fillstyle' : 1001,
        'linecolor' : 420,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + b#bar{b}",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu' : {
        'files' : ['DYJetsToNuNu'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu_HT' : {
        'files' : ['ZJetsToNuNu_HT-100To200', 'ZJetsToNuNu_HT-200To400', 'ZJetsToNuNu_HT-400To600', 'ZJetsToNuNu_HT-600To800', 'ZJetsToNuNu_HT-800To1200', 'ZJetsToNuNu_HT-1200To2500', 'ZJetsToNuNu_HT-2500ToInf'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu-0b' : {
        'files' : ['ZJetsToNuNu_HT-100To200', 'ZJetsToNuNu_HT-200To400', 'ZJetsToNuNu_HT-400To600', 'ZJetsToNuNu_HT-600To800', 'ZJetsToNuNu_HT-800To1200', 'ZJetsToNuNu_HT-1200To2500', 'ZJetsToNuNu_HT-2500ToInf'],
        'fillcolor' : 851,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu-1b' : {
        'files' : ['ZJetsToNuNu_HT-100To200', 'ZJetsToNuNu_HT-200To400', 'ZJetsToNuNu_HT-400To600', 'ZJetsToNuNu_HT-600To800', 'ZJetsToNuNu_HT-800To1200', 'ZJetsToNuNu_HT-1200To2500', 'ZJetsToNuNu_HT-2500ToInf'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 855,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + b",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu-2b' : {
        'files' : ['ZJetsToNuNu_HT-100To200', 'ZJetsToNuNu_HT-200To400', 'ZJetsToNuNu_HT-400To600', 'ZJetsToNuNu_HT-600To800', 'ZJetsToNuNu_HT-800To1200', 'ZJetsToNuNu_HT-1200To2500', 'ZJetsToNuNu_HT-2500ToInf'],
        'fillcolor' : 855,
        'fillstyle' : 1001,
        'linecolor' : 854,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + b#bar{b}",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu_Pt' : {
        'files' : ['DYJetsToNuNu_Pt-100To250', 'DYJetsToNuNu_Pt-250To400', 'DYJetsToNuNu_Pt-400To650', 'DYJetsToNuNu_Pt-650ToInf'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu_Pt-0b' : {
        'files' : ['DYJetsToNuNu_Pt-100To250', 'DYJetsToNuNu_Pt-250To400', 'DYJetsToNuNu_Pt-400To650', 'DYJetsToNuNu_Pt-650ToInf'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu_Pt-1b' : {
        'files' : ['DYJetsToNuNu_Pt-100To250', 'DYJetsToNuNu_Pt-250To400', 'DYJetsToNuNu_Pt-400To650', 'DYJetsToNuNu_Pt-650ToInf'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + b",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToNuNu_Pt-2b' : {
        'files' : ['DYJetsToNuNu_Pt-100To250', 'DYJetsToNuNu_Pt-250To400', 'DYJetsToNuNu_Pt-400To650', 'DYJetsToNuNu_Pt-650ToInf'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(#nu#nu) + b#bar{b}",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu' : {
        'files' : ['WJetsToLNu'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu_HT' : {
        'files' : ['WJetsToLNu_HT-70To100', 'WJetsToLNu_HT-100To200', 'WJetsToLNu_HT-200To400', 'WJetsToLNu_HT-400To600', 'WJetsToLNu_HT-600To800', 'WJetsToLNu_HT-800To1200', 'WJetsToLNu_HT-1200To2500', 'WJetsToLNu_HT-2500ToInf', 'WJetsToQQ_HT-600ToInf'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu-0b' : {
        'files' : ['WJetsToLNu_HT-100To200', 'WJetsToLNu_HT-200To400', 'WJetsToLNu_HT-400To600', 'WJetsToLNu_HT-600To800', 'WJetsToLNu_HT-800To1200', 'WJetsToLNu_HT-1200To2500', 'WJetsToLNu_HT-2500ToInf', 'WJetsToQQ_HT-600ToInf'],
        'fillcolor' : 886,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu-1b' : {
        'files' : ['WJetsToLNu_HT-100To200', 'WJetsToLNu_HT-200To400', 'WJetsToLNu_HT-400To600', 'WJetsToLNu_HT-600To800', 'WJetsToLNu_HT-800To1200', 'WJetsToLNu_HT-1200To2500', 'WJetsToLNu_HT-2500ToInf', 'WJetsToQQ_HT-600ToInf'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 882,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + b",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu-2b' : {
        'files' : ['WJetsToLNu_HT-100To200', 'WJetsToLNu_HT-200To400', 'WJetsToLNu_HT-400To600', 'WJetsToLNu_HT-600To800', 'WJetsToLNu_HT-800To1200', 'WJetsToLNu_HT-1200To2500', 'WJetsToLNu_HT-2500ToInf', 'WJetsToQQ_HT-600ToInf'],
        'fillcolor' : 882,
        'fillstyle' : 1001,
        'linecolor' : 883,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + b#bar{b}",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu_Pt-0b' : {
        'files' : ['WJetsToLNu_Pt-100To250', 'WJetsToLNu_Pt-250To400', 'WJetsToLNu_Pt-400To600', 'WJetsToLNu_Pt-600ToInf'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu_Pt-1b' : {
        'files' : ['WJetsToLNu_Pt-100To250', 'WJetsToLNu_Pt-250To400', 'WJetsToLNu_Pt-400To600', 'WJetsToLNu_Pt-600ToInf'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + b",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu_Pt-2b' : {
        'files' : ['WJetsToLNu_Pt-100To250', 'WJetsToLNu_Pt-250To400', 'WJetsToLNu_Pt-400To600', 'WJetsToLNu_Pt-600ToInf'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + b#bar{b}",
        'weight': 1.,
        'plot': True,
    },
    'WJetsToLNu_Pt' : {
        'files' : ['WJetsToLNu_Pt-100To250', 'WJetsToLNu_Pt-250To400', 'WJetsToLNu_Pt-400To600', 'WJetsToLNu_Pt-600ToInf'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W(l#nu) + jets",
        'weight': 1.,
        'plot': True,
    },
    'TTbar' : {
        'files' : ['TT', 'TTWJetsToLNu', 'TTZToLLNuNu'],
#        'files' : ['TTTo2L2Nu', 'TTToSemiLeptonic', 'TTWJetsToLNu', 'TTZToLLNuNu'],
        'fillcolor' : 798,
        'fillstyle' : 1001,
        'linecolor' : 798,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t#bar{t}",#, single t
        'weight': 1.,
        'plot': True,
    },
    'TTbarSL' : {
        'files' : ['TTTo2L2Nu', 'TTToSemiLeptonic', 'TTWJetsToLNu', 'TTZToLLNuNu'],
        'fillcolor' : 798,
        'fillstyle' : 1001,
        'linecolor' : 798,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t#bar{t}",#, single t
        'weight': 1.,
        'plot': True,
    },
    'ST' : {
        'files' : ['ST_s-channel', 'ST_t-channel_antitop', 'ST_t-channel_top', 'ST_tW_antitop', 'ST_tW_top'],
        'fillcolor' : 801,
        'fillstyle' : 1001,
        'linecolor' : 801,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t+X",
        'weight': 1.,
        'plot': True,
    },
    'VV' : {
        'files' : ['WWTo1L1Nu2Q', 'WWTo2L2Nu', 'WWTo4Q', 'WZTo1L1Nu2Q', 'WZTo2L2Q', 'WZTo2Q2Nu', 'ZZTo2L2Q', 'ZZTo2Q2Nu', 'ZZTo2L2Nu', 'ZZTo4L', 'ZZTo4Q', 'GluGluHToBB', 'WHToLNuBB', 'ZHToLLBB', 'ZHToNuNuBB', 'ZHToQQBB'],
        'fillcolor' : 602,
        'fillstyle' : 1001,
        'linecolor' : 602,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "VV, VH",
        'weight': 1.,
        'plot': True,
    },
    'Higgs' : {
        'files' : ['GluGluHToBB', 'WHToLNuBB', 'ZHToLLBB', 'ZHToNuNuBB', 'ZHToQQBB'],
        'fillcolor' : 628,
        'fillstyle' : 1001,
        'linecolor' : 629,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "SM Higgs",
        'weight': 1.,
        'plot': True,
    },
    'QCD' : {
        'files' : ['QCD_HT100to200', 'QCD_HT200to300', 'QCD_HT300to500', 'QCD_HT500to700', 'QCD_HT700to1000', 'QCD_HT1000to1500', 'QCD_HT1500to2000', 'QCD_HT2000toInf'],
        'fillcolor' : 921,
        'fillstyle' : 1001,
        'linecolor' : 921,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "multijet",
        'weight': 1.,
        'plot': True,
    },
    'QCD_HT100to200' : {'files' : ['QCD_HT100to200'], 'fillcolor' : 916, 'fillstyle' : 1001, 'linecolor' : 921, 'linewidth' : 2, 'linestyle' : 1, 'label' : "QCD HT 100to200", 'weight': 1., 'plot': True,},
    'QCD_HT200to300' : {'files' : ['QCD_HT200to300'], 'fillcolor' : 917, 'fillstyle' : 1001, 'linecolor' : 921, 'linewidth' : 2, 'linestyle' : 1, 'label' : "QCD HT 200to300", 'weight': 1., 'plot': True,},
    'QCD_HT300to500' : {'files' : ['QCD_HT300to500'], 'fillcolor' : 918, 'fillstyle' : 1001, 'linecolor' : 921, 'linewidth' : 2, 'linestyle' : 1, 'label' : "QCD HT 300to500", 'weight': 1., 'plot': True,},
    'QCD_HT500to700' : {'files' : ['QCD_HT500to700'], 'fillcolor' : 919, 'fillstyle' : 1001, 'linecolor' : 921, 'linewidth' : 2, 'linestyle' : 1, 'label' : "QCD HT 500to700", 'weight': 1., 'plot': True,},
    'QCD_HT700to1000' : {'files' : ['QCD_HT700to1000'], 'fillcolor' : 920, 'fillstyle' : 1001, 'linecolor' : 921, 'linewidth' : 2, 'linestyle' : 1, 'label' : "QCD HT 700to1000", 'weight': 0.891, 'plot': True,},
    'QCD_HT1000to1500' : {'files' : ['QCD_HT1000to1500'], 'fillcolor' : 921, 'fillstyle' : 1001, 'linecolor' : 921, 'linewidth' : 2, 'linestyle' : 1, 'label' : "QCD HT 1000to1500", 'weight': 0.815, 'plot': True,},
    'QCD_HT1500to2000' : {'files' : ['QCD_HT1500to2000'], 'fillcolor' : 922, 'fillstyle' : 1001, 'linecolor' : 921, 'linewidth' : 2, 'linestyle' : 1, 'label' : "QCD HT 1500to2000", 'weight': 0.823, 'plot': True,},
    'QCD_HT2000toInf' : {'files' : ['QCD_HT2000toInf'], 'fillcolor' : 923, 'fillstyle' : 1001, 'linecolor' : 921, 'linewidth' : 2, 'linestyle' : 1, 'label' : "QCD HT 2000toInf", 'weight': 0.642, 'plot': True,},
    
    'AllBkg' : {
        'files' : [],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "All backgrounds",
        'weight': 1.,
        'plot': True,
    },
    
        
    # Dummy entry for background sum
    'BkgSum' : {
        'order' : 0,
        'files' : [],
        'fillcolor' : 1,
        'fillstyle' : 3003,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "MC stat.",
        'weight': 1.,
        'plot': True,
    },
    
    'PreFit' : {
        'order' : 0,
        'files' : [],
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 923,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "Pre-fit",
        'weight': 1.,
        'plot': True,
    },
    

#################### XZH Signals 623 625 628 629 633 634 635 636
    'XZH_M600' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-600', 'ZprimeToZhToZinvhbb_narrow_M-600', 'ZprimeToZhToZlephbb_narrow_M-600'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZH_M800' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-800', 'ZprimeToZhToZinvhbb_narrow_M-800', 'ZprimeToZhToZlephbb_narrow_M-800'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZH_M1000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-1000', 'ZprimeToZhToZinvhbb_narrow_M-1000', 'ZprimeToZhToZlephbb_narrow_M-1000'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZH_M1200' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-1200', 'ZprimeToZhToZinvhbb_narrow_M-1200', 'ZprimeToZhToZlephbb_narrow_M-1200'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1200 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZH_M1400' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-1400', 'ZprimeToZhToZinvhbb_narrow_M-1400', 'ZprimeToZhToZlephbb_narrow_M-1400'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1400 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZH_M1600' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-1600', 'ZprimeToZhToZinvhbb_narrow_M-1600', 'ZprimeToZhToZlephbb_narrow_M-1600'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZH_M1800' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-1800', 'ZprimeToZhToZinvhbb_narrow_M-1800', 'ZprimeToZhToZlephbb_narrow_M-1800'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZH_M2000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-2000', 'ZprimeToZhToZinvhbb_narrow_M-2000', 'ZprimeToZhToZlephbb_narrow_M-2000'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 2000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZH_M2500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-2500', 'ZprimeToZhToZinvhbb_narrow_M-2500', 'ZprimeToZhToZlephbb_narrow_M-2500'],
        'fillcolor' : 629,
        'fillstyle' : 3005,
        'linecolor' : 633,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 2500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZH_M3000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-3000', 'ZprimeToZhToZinvhbb_narrow_M-3000', 'ZprimeToZhToZlephbb_narrow_M-3000'],
        'fillcolor' : 633,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 3000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZH_M3500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-3500', 'ZprimeToZhToZinvhbb_narrow_M-3500', 'ZprimeToZhToZlephbb_narrow_M-3500'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 3500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZH_M4000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-4000', 'ZprimeToZhToZinvhbb_narrow_M-4000', 'ZprimeToZhToZlephbb_narrow_M-4000'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 4000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZH_M4500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZhadhbb_narrow_M-4500', 'ZprimeToZhToZinvhbb_narrow_M-4500', 'ZprimeToZhToZlephbb_narrow_M-4500'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 4500 GeV",
        'weight': 1.,
        'plot': False,
    },

###

    'XZHll_M600' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-600'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHll_M800' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-800'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHll_M1000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-1000'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZHll_M1200' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-1200'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1200 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHll_M1400' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-1400'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1400 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHll_M1600' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-1600'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHll_M1800' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-1800'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHll_M2000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-2000'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 2000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZHll_M2500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-2500'],
        'fillcolor' : 629,
        'fillstyle' : 3005,
        'linecolor' : 633,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 2500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHll_M3000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-3000'],
        'fillcolor' : 633,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 3000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZHll_M3500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-3500'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 3500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHll_M4000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-4000'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 4000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZHll_M4500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZlephbb_narrow_M-4500'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 4500 GeV",
        'weight': 1.,
        'plot': False,
    },
    
###

    'XZHnn_M600' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-600'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHnn_M800' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-800'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHnn_M1000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-1000'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZHnn_M1200' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-1200'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1200 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHnn_M1400' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-1400'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1400 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHnn_M1600' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-1600'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHnn_M1800' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-1800'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 1800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHnn_M2000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-2000'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 2000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZHnn_M2500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-2500'],
        'fillcolor' : 629,
        'fillstyle' : 3005,
        'linecolor' : 633,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 2500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHnn_M3000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-3000'],
        'fillcolor' : 633,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 3000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZHnn_M3500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-3500'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 3500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XZHnn_M4000' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-4000'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 4000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XZHnn_M4500' : {
        'order' : 1001,
        'files' : ['ZprimeToZhToZinvhbb_narrow_M-4500'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{Z'} = 4500 GeV",
        'weight': 1.,
        'plot': False,
    },

###

    'XWHln_M600' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-600'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWHln_M800' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-800'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWHln_M1000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-1000'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 1000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWHln_M1200' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-1200'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 1200 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWHln_M1400' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-1400'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 1400 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWHln_M1600' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-1600'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 1600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWHln_M1800' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-1800'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 1800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWHln_M2000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-2000'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 2000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWHln_M2500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-2500'],
        'fillcolor' : 629,
        'fillstyle' : 3005,
        'linecolor' : 633,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 2500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWHln_M3000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-3000'],
        'fillcolor' : 633,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 3000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWHln_M3500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-3500'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 3500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWHln_M4000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-4000'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 4000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWHln_M4500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWlephbb_narrow_M-4500'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 4500 GeV",
        'weight': 1.,
        'plot': False,
    },

###

    'XWH_M600' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-600', 'WprimeToWhToWlephbb_narrow_M-600'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWH_M800' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-800', 'WprimeToWhToWlephbb_narrow_M-800'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWH_M1000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-1000', 'WprimeToWhToWlephbb_narrow_M-1000'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 1000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWH_M1200' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-1200', 'WprimeToWhToWlephbb_narrow_M-1200'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 1200 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWH_M1400' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-1400', 'WprimeToWhToWlephbb_narrow_M-1400'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 1400 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWH_M1600' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-1600', 'WprimeToWhToWlephbb_narrow_M-1600'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 1600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWH_M1800' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-1800', 'WprimeToWhToWlephbb_narrow_M-1800'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 1800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWH_M2000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-2000', 'WprimeToWhToWlephbb_narrow_M-2000'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 2000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWH_M2500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-2500', 'WprimeToWhToWlephbb_narrow_M-2500'],
        'fillcolor' : 629,
        'fillstyle' : 3005,
        'linecolor' : 633,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 2500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWH_M3000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-3000', 'WprimeToWhToWlephbb_narrow_M-3000'],
        'fillcolor' : 633,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 3000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWH_M3500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-3500', 'WprimeToWhToWlephbb_narrow_M-3500'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 3500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XWH_M4000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-4000', 'WprimeToWhToWlephbb_narrow_M-4000'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 4000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XWH_M4500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-4500', 'WprimeToWhToWlephbb_narrow_M-4500'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{W'} = 4500 GeV",
        'weight': 1.,
        'plot': False,
    },

###

    'XVH_M600' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-600', 'ZprimeToZhToZhadhbb_narrow_M-600', 'ZprimeToZhToZinvhbb_narrow_M-600', 'WprimeToWhToWlephbb_narrow_M-600', 'ZprimeToZhToZlephbb_narrow_M-600'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XVH_M800' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-800', 'ZprimeToZhToZhadhbb_narrow_M-800', 'ZprimeToZhToZinvhbb_narrow_M-800', 'WprimeToWhToWlephbb_narrow_M-800', 'ZprimeToZhToZlephbb_narrow_M-800'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XVH_M1000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-1000', 'ZprimeToZhToZhadhbb_narrow_M-1000', 'ZprimeToZhToZinvhbb_narrow_M-1000', 'WprimeToWhToWlephbb_narrow_M-1000', 'ZprimeToZhToZlephbb_narrow_M-1000'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 1000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XVH_M1200' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-1200', 'ZprimeToZhToZhadhbb_narrow_M-1200', 'ZprimeToZhToZinvhbb_narrow_M-1200', 'WprimeToWhToWlephbb_narrow_M-1200', 'ZprimeToZhToZlephbb_narrow_M-1200'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 1200 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XVH_M1400' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-1400', 'ZprimeToZhToZhadhbb_narrow_M-1400', 'ZprimeToZhToZinvhbb_narrow_M-1400', 'WprimeToWhToWlephbb_narrow_M-1400', 'ZprimeToZhToZlephbb_narrow_M-1400'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 1400 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XVH_M1600' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-1600', 'ZprimeToZhToZhadhbb_narrow_M-1600', 'ZprimeToZhToZinvhbb_narrow_M-1600', 'WprimeToWhToWlephbb_narrow_M-1600', 'ZprimeToZhToZlephbb_narrow_M-1600'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 1600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XVH_M1800' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-1800', 'ZprimeToZhToZhadhbb_narrow_M-1800', 'ZprimeToZhToZinvhbb_narrow_M-1800', 'WprimeToWhToWlephbb_narrow_M-1800', 'ZprimeToZhToZlephbb_narrow_M-1800'],
        'fillcolor' : 629,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 1800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XVH_M2000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-2000', 'ZprimeToZhToZhadhbb_narrow_M-2000', 'ZprimeToZhToZinvhbb_narrow_M-2000', 'WprimeToWhToWlephbb_narrow_M-2000', 'ZprimeToZhToZlephbb_narrow_M-2000'],
        'fillcolor' : 629,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 2000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XVH_M2500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-2500', 'ZprimeToZhToZhadhbb_narrow_M-2500', 'ZprimeToZhToZinvhbb_narrow_M-2500', 'WprimeToWhToWlephbb_narrow_M-2500', 'ZprimeToZhToZlephbb_narrow_M-2500'],
        'fillcolor' : 633,
        'fillstyle' : 3005,
        'linecolor' : 633,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 2500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XVH_M3000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-3000', 'ZprimeToZhToZhadhbb_narrow_M-3000', 'ZprimeToZhToZinvhbb_narrow_M-3000', 'WprimeToWhToWlephbb_narrow_M-3000', 'ZprimeToZhToZlephbb_narrow_M-3000'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 3000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XVH_M3500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-3500', 'ZprimeToZhToZhadhbb_narrow_M-3500', 'ZprimeToZhToZinvhbb_narrow_M-3500', 'WprimeToWhToWlephbb_narrow_M-3500', 'ZprimeToZhToZlephbb_narrow_M-3500'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 3500 GeV",
        'weight': 1.,
        'plot': False,
    },
    'XVH_M4000' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-4000', 'ZprimeToZhToZhadhbb_narrow_M-4000', 'ZprimeToZhToZinvhbb_narrow_M-4000', 'WprimeToWhToWlephbb_narrow_M-4000', 'ZprimeToZhToZlephbb_narrow_M-4000'],
        'fillcolor' : 636,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 4000 GeV",
        'weight': 1.,
        'plot': True,
    },
    'XVH_M4500' : {
        'order' : 1001,
        'files' : ['WprimeToWhToWhadhbb_narrow_M-4500', 'ZprimeToZhToZhadhbb_narrow_M-4500', 'ZprimeToZhToZinvhbb_narrow_M-4500', 'WprimeToWhToWlephbb_narrow_M-4500', 'ZprimeToZhToZlephbb_narrow_M-4500'],
        'fillcolor' : 636,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{V'} = 4500 GeV",
        'weight': 1.,
        'plot': False,
    },





################# AZh

    'AZh_M225' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M225', 'GluGluToAToZhToNuNuBB_M225'],
        'fillcolor' : 623,
        'fillstyle' : 3005,
        'linecolor' : 623,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 225 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M250' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M250', 'GluGluToAToZhToNuNuBB_M250'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 250 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M275' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M275', 'GluGluToAToZhToNuNuBB_M275'],
        'fillcolor' : 628,
        'fillstyle' : 3005,
        'linecolor' : 628,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 275 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M300' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M300', 'GluGluToAToZhToNuNuBB_M300'],
        'fillcolor' : 629,
        'fillstyle' : 3005,
        'linecolor' : 629,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 300 GeV",
        'weight': 1.,
        'plot': True,
    },
    'AZh_M325' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M325', 'GluGluToAToZhToNuNuBB_M325'],
        'fillcolor' : 633,
        'fillstyle' : 3005,
        'linecolor' : 633,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 325 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M350' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M350', 'GluGluToAToZhToNuNuBB_M350'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 350 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M400' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M400', 'GluGluToAToZhToNuNuBB_M400'],
        'fillcolor' : 635,
        'fillstyle' : 3005,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 400 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M500' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M500', 'GluGluToAToZhToNuNuBB_M500'],
        'fillcolor' : 636,
        'fillstyle' : 3005,
        'linecolor' : 636,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 500 GeV",
        'weight': 1.,
        'plot': True,
    },
    'AZh_M600' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M600', 'GluGluToAToZhToNuNuBB_M600'],
        'fillcolor' : 1,
        'fillstyle' : 3005,
        'linecolor' : 1,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M700' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M700', 'GluGluToAToZhToNuNuBB_M700'],
        'fillcolor' : 1,
        'fillstyle' : 3005,
        'linecolor' : 1,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 700 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M750' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M750', 'GluGluToAToZhToNuNuBB_M750'],
        'fillcolor' : 1,
        'fillstyle' : 3005,
        'linecolor' : 1,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 750 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M800' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M800', 'GluGluToAToZhToNuNuBB_M800'],
        'fillcolor' : 1,
        'fillstyle' : 3005,
        'linecolor' : 1,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 800 GeV",
        'weight': 1.,
        'plot': True,
    },
    'AZh_M900' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M900', 'GluGluToAToZhToNuNuBB_M900'],
        'fillcolor' : 1,
        'fillstyle' : 3005,
        'linecolor' : 1,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 900 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M1000' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M1000', 'GluGluToAToZhToNuNuBB_M1000'],
        'fillcolor' : 1,
        'fillstyle' : 3005,
        'linecolor' : 1,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 1000 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M1200' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M1200', 'GluGluToAToZhToNuNuBB_M1200'],
        'fillcolor' : 1,
        'fillstyle' : 3005,
        'linecolor' : 1,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 1200 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M1400' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M1400', 'GluGluToAToZhToNuNuBB_M1400'],
        'fillcolor' : 1,
        'fillstyle' : 3005,
        'linecolor' : 1,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 1400 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M1600' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M1600', 'GluGluToAToZhToNuNuBB_M1600'],
        'fillcolor' : 1,
        'fillstyle' : 3005,
        'linecolor' : 1,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 1600 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M1800' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M1800', 'GluGluToAToZhToNuNuBB_M1800'],
        'fillcolor' : 1,
        'fillstyle' : 3005,
        'linecolor' : 1,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 1800 GeV",
        'weight': 1.,
        'plot': False,
    },
    'AZh_M2000' : {
        'order' : 1001,
        'files' : ['GluGluToAToZhToLLBB_M2000', 'GluGluToAToZhToNuNuBB_M2000'],
        'fillcolor' : 1,
        'fillstyle' : 3005,
        'linecolor' : 1,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{A} = 2000 GeV",
        'weight': 1.,
        'plot': False,
    },



################# DM

    'tDM_MChi1_MPhi100' : {
        'order' : 1001,
        'files' : ['DMScalar_top_tChan_MChi1_MPhi100', 'DMScalar_top_tWChan_MChi1_MPhi100'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t+DM, m_{#phi}=100 GeV",
        'weight': 1.,
        'plot': False,
    },
    'tDM_MChi1_MPhi300' : {
        'order' : 1001,
        'files' : ['DMScalar_top_tChan_MChi1_MPhi300', 'DMScalar_top_tWChan_MChi1_MPhi300'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t+DM, m_{#phi}=300 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    'ttDM_MChi1_MPhi10' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-10'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=10 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    'ttDM_MChi1_MPhi20' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-20'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=20 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    'ttDM_MChi1_MPhi50' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-50'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=50 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    'ttDM_MChi1_MPhi100' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-100'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=100 GeV",
        'weight': 1.,
        'plot': True,
    },
    
    'ttDM_MChi1_MPhi200' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-200'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=200 GeV",
        'weight': 1.,
        'plot': False,
    },

    'ttDM_MChi1_MPhi300' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-300'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=300 GeV",
        'weight': 1.,
        'plot': True,
    },
    
    'ttDM_MChi1_MPhi500' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-500'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=500 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    'ttDM_MChi1_MPhi1000' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-1000'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 2,
        'label' : "tt+DM, m_{#phi}=1000 GeV",
        'weight': 1.,
        'plot': False,
    },
    
    
    'tttDM_MChi1_MPhi100' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-100', 'DMScalar_top_tChan_MChi1_MPhi100', 'DMScalar_top_tWChan_MChi1_MPhi100'],
        'fillcolor' : 625,
        'fillstyle' : 3005,
        'linecolor' : 625,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t, tt+DM, m_{#phi}=100 GeV",
        'weight': 1.,
        'plot': True,
    },
    'tttDM_MChi1_MPhi300' : {
        'order' : 1001,
        'files' : ['TTbarDMJets_scalar_Mchi-1_Mphi-300', 'DMScalar_top_tChan_MChi1_MPhi300', 'DMScalar_top_tWChan_MChi1_MPhi300'],
        'fillcolor' : 634,
        'fillstyle' : 3005,
        'linecolor' : 634,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "t, tt+DM, m_{#phi}=300 GeV",
        'weight': 1.,
        'plot': True,
    },
}

################# Mono-H

for mZ in [800, 1000, 1200, 1400, 1700, 2000, 2500, 2750, 3000, 3500, 4000]:
   for mA in [300, 400, 500, 600, 700, 800]:
       if mZ in [800] and mA in [700, 800]: continue
       if mZ in [2750, 3000, 3500, 4000] and mA in [400, 600, 700]: continue
       sample["monoH_MZ%d_MA%d" % (mZ, mA)] = {'order' : 1001, 'files' : ["ZprimeToA0hToA0chichihbb_2HDM_MZp-%d_MA0-%d" % (mZ, mA)], 'fillcolor' : 636, 'fillstyle' : 3005, 'linecolor' : 636, 'linewidth' : 3, 'linestyle' : 1, 'label' : "m_{Z'} = %d GeV, m_{A} = %d GeV" % (mZ, mA), 'weight': 1., 'plot': False,}

