#! /usr/bin/env python

variable = {
    'nPV': {
        'title' : "number of primary vertices",
        'nbins' : 51,
        'min' : -0.5,
        'max' : 50.5,
        'log' : False,
    },
    'nElectrons': {
        'title' : "number of electrons",
        'nbins' : 5,
        'min' : -0.5,
        'max' : 4.5,
        'log' : True,
    },
    'nMuons': {
        'title' : "number of muons",
        'nbins' : 5,
        'min' : -0.5,
        'max' : 4.5,
        'log' : True,
    },
     'nTaus': {
        'title' : "number of #tau",
        'nbins' : 5,
        'min' : -0.5,
        'max' : 4.5,
        'log' : True,
    },
    'nJets': {
        'title' : "number of AK4 jets",
        'nbins' : 13,
        'min' : -0.5,
        'max' : 12.5,
        'log' : True,
    },
    'nForwardJets': {
        'title' : "number of forward AK4 jets",
        'nbins' : 10,
        'min' : -0.5,
        'max' : 9.5,
        'log' : True,
    },
    'nBJets': {
        'title' : "number of AK4 jets",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'log' : True,
    },
    'nBQuarks': {
        'title' : "number of AK4 jets",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'log' : True,
    },
   'nBTagJets': {
        'title' : "number of b-tagged AK4 jets",
        'nbins' : 7,
        'min' : -0.5,
        'max' : 6.5,
        'log' : True,
    },
    'MET_pt': {
        'title' : "#slash{E}_{T} (GeV)",
        #'bins' : [250, 320, 400, 500, 650, 850, 1200, 1600, 2000],
        #'bins' : [250, 320, 400, 500, 625, 775, 950, 1200, 1500],
        'nbins' : 14,
        'min' : 250,
        'max' : 530,
        # 'nbins' : -1, #30,
        # 'min' : 250,
        # 'max' : 1450,
        'log' : True,
    },
    'MET_phi': {
        'title' : "#slash{E}_{T} #phi",
        'nbins' : 36,
        'min' : -3.15,
        'max' : 3.15,
        'log' : False,
    },
    'JetF_phi': {
        'title' : "jforw #phi",
        'nbins' : 36,
        'min' : -3.15,
        'max' : 3.15,
        'log' : False,
    },
    'Jet1_phi': {
        'title' : "j1 #phi",
        'nbins' : 36,
        'min' : -3.15,
        'max' : 3.15,
        'log' : False,
    },
    'Jet2_phi': {
        'title' : "j2 #phi",
        'nbins' : 36,
        'min' : -3.15,
        'max' : 3.15,
        'log' : False,
    },
    'MET_sign': { 
        'title' : "#slash{E}_{T} (GeV)", #"#slash{E}_{T} significance",
        # 'bins' : [160, 200, 250, 320, 400, 500, 650, 900, 1200],
        # 'nbins' : -1, #30,
        # 'min' : 250,
        # 'max' : 1450,
        'nbins' : 8,
        'min' : 160,
        'max' : 480,
        'log' : False,
    },
    'FakeMET_pt': {
        'title' : "Hadronic recoil (GeV)",
        #'bins' : [250, 320, 400, 500, 650, 900, 1200, 1600, 2000],
        # 'bins' : [250, 320, 400, 500, 625, 775, 950, 1200, 1500],
        # 'nbins' : -1, #30,
        # 'min' : 250,
        # 'max' : 1450,
        # 'log' : True,
        'nbins' : 14,
        'min' : 250,
        'max' : 530,
        'log' : True,
    },
    'mTbHT': {
        'title' : "mTb+HT (GeV)",
        'nbins' : 25,
        'min' : 0,
        'max' : 2000.,
        'log' : True,
    },
    'mTbHTratio': {
        'title' : "mTb+HT ratio",
        'nbins' : 20,
        'min' : 0,
        'max' : 5.,
        'log' : True,
    },
    'HT': {
        'title' : "HT (GeV)",
        'nbins' : 20,
        'min' : 30,
        'max' : 1030.,
        'log' : True,
    },
    'HT3': {
        'title' : "HT3 (GeV)",
        'nbins' : 25,
        'min' : 0,
        'max' : 1000.,
        'log' : True,
    },

    'CFT': {
        'title' : "CFT",
        'nbins' : 20,
        'min' : 0,
        'max' : 1.,
        'log' : False,
    },
    'DFT': {
        'title' : "DFT",
        'nbins' : 10,
        'min' : 0,
        'max' : 0.5,
        'log' : False,
    },
    'sphericityFT': {
        'title' : "sphericityFT",
        'nbins' : 20,
        'min' : 0,
        'max' : 1.,
        'log' : False,
    },
    'sphericity_AZFT': {
        'title' : "sphericity_AZFT",
        'nbins' : 20,
        'min' : 0,
        'max' : 1.,
        'log' : False,
    },
    'circularityFT': {
        'title' : "circularityFT",
        'nbins' : 20,
        'min' : 0,
        'max' : 1.,
        'log' : False,
    },
    'aplanarityFT': {
        'title' : "aplanarityFT",
        'nbins' : 10,
        'min' : 0,
        'max' : 0.5,
        'log' : False,
    },

    'HTratio': {
        'title' : "HTratio (GeV)",
        'nbins' : 10,
        'min' : 0,
        'max' : 1.,
        'log' : True,
    },
    'ST': {
        'title' : "HT (GeV)",
        'nbins' : 20,
        'min' : 0,
        'max' : 2000.,
        'log' : True,
    },
    'DeltaPhi': {
        'title' : "cos(#Delta#phi(lep1,MET)",
        'nbins' : 16,
        'min' : 0,
        'max' : 1.,
        'log' : True,
    },

    'Dphi_topb': {
        'title' : "#Delta #varphi (top,b)",
        'nbins' : 16,
        'min' : 0,
        'max' : 3.2,
        'log' : True,
    },
    'Dphi_Wb': {
        'title' : "#Delta #varphi (W,b)",
        'nbins' : 16,
        'min' : 0,
        'max' : 3.2,
        'log' : True,
    },
    'Dphi_topMET': {
        'title' : "#Delta #varphi (top,MET)",
        'nbins' : 16,
        'min' : 0,
        'max' : 3.2,
        'log' : True,
    },
    'Dphi_WMET': {
        'title' : "#Delta #varphi (W,MET)",
        'nbins' : 16,
        'min' : 0,
        'max' : 3.2,
        'log' : True,
    },


    'minDphiJet1BJet': {
        'title' : "min #Delta #varphi (b-jet,jet1)",
        'nbins' : 16,
        'min' : 0,
        'max' : 3.2,
        'log' : False,
    },
    'minDphiJet2BJet': {
        'title' : "min #Delta #varphi (b-jet,jet2)",
        'nbins' : 16,
        'min' : 0,
        'max' : 3.2,
        'log' : False,
    },
    'MinDPhi': {
        'title' : "min #Delta #varphi (jet-#slash{E}_{T})",
        'nbins' : 16,
        'min' : 0,
        'max' : 3.2,
        'log' : True,
    },
    'MinDPhi12': {
        'title' : "min #Delta #varphi (jet_{1,2}-#slash{E}_{T})",
        'nbins' : 15,
        'min' : 0,
        'max' : 3.,
        'log' : False,
    },
    'MinLepJetDPhi': {
        'title' : "min #Delta #varphi (lep,jets)",
        'nbins' : 28,
        'min' : 0,
        'max' : 3.15,
        'log' : False,
    },
    'MinLepMetDPhi': {
        'title' : "min #Delta #varphi (lep,MET)",
        'nbins' : 28,
        'min' : 0,
        'max' : 3.15,
        'log' : True,
    },
    'MinBJetMetDPhi': {
        'title' : "min #Delta #varphi (bjet,#slash{E}_{T})",
        'nbins' : 28,
        'min' : 0,
        'max' : 3.15,
        'log' : True,
    },
    'MaxJetMetDPhi': {
        'title' : "max #Delta #varphi (jet,#slash{E}_{T})",
        'nbins' : 28,
        'min' : 0,
        'max' : 3.15,
        'log' : True,
    },
    'MaxBJetMetDPhi': {
        'title' : "max #Delta #varphi (bjet-#slash{E}_{T})",
        'nbins' : 28,
        'min' : 0,
        'max' : 3.15,
        'log' : True,
    },
    'MaxLepMetDPhi': {
        'title' : "max #Delta #varphi (lep,MET)",
        'nbins' : 28,
        'min' : 0,
        'max' : 3.15,
        'log' : True,
    },
    'MaxLepJetDPhi': {
        'title' : "max #Delta #varphi (lep,jet)",
        'nbins' : 28,
        'min' : 0,
        'max' : 3.15,
        'log' : True,
    },

    'mZ': {
        'title' : "Z mass (GeV)",
        'nbins' : 60,
        'min' : 60,
        'max' : 120,
        'log' : False,
    },
    'mTop': {
        'title' : "top mass (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : False,
    },
    'mW': {
        'title' : "W mass (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : False,
    },
    'topMass': {
        'title' : "top mass (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : False,
    },
    'WMass': {
        'title' : "W mass (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : False,
    },
    'topdRMass': {
        'title' : "top dR mass (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : False,
    },
    'WdRMass': {
        'title' : "W dR mass (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : False,
    },
    'mT': {
        'title' : "m_{T}^{W} (GeV)",
        #'nbins' : 22,
        # 'min' : 0,
        # 'max' : 550,
        'nbins' : 16,
        'min' : 160,
        'max' : 560,
        # 'min' : 0,
        # 'max' : 400,
        'log' : False,
    },
    'mTjets': {
        'title' : "m_{T} jets (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : False,
    },

    'mTb': {
        'title' : "m_{T}^{b} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'mTb_nullMass': {
        'title' : "m_{T}^{b} (GeV)",
        'nbins' : 20,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'mTl1': {
        'title' : "m_{T}^{W} (GeV)",
        'nbins' : 20,
        'min' : 0,
        'max' : 600,
        'log' : True,
    },
    'mTl2': {
        'title' : "m_{T}l1 (GeV)",
        'nbins' : 20,
        'min' : 0,
        'max' : 600,
        'log' : True,
    },
    'mtJetMET': {
        'title' : "m_{T}l2 (GeV)",
        'nbins' : 20,
        'min' : 0,
        'max' : 800,
        'log' : True,
    },

    'mT2': {
        'title' : "m_{T2}^{W} (GeV)",
        'nbins' : 10,
        'min' : 80,
        'max' : 480,
        'log' : False,
    },
    'V_pt': {
        'title' : "Z p_{T} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 2000,
        'log' : True,
    },
    'Lepton1_pt': {
        'title' : "lepton 1 p_{T} (GeV)",
        'nbins' : 16,
        'min' : 30,
        'max' : 350,
        'log' : False,
    },
    'Lepton1_phi': {
        'title' : "lepton 1 #phi",
        'nbins' : 36,
        'min' : -3.15,
        'max' : 3.15,
        'log' : False,
    },
    'Lepton2_pt': {
        'title' : "lepton 2 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'Lepton1_pfIso': {
        'title' : "lepton 1 isolation (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 5,
        'log' : True,
    },
    'Lepton2_pfIso': {
        'title' : "lepton 2 isolation (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 5,
        'log' : True,
    },

    'DeltaR_bb':{
        'title' : "#DeltaR(b,b) (GeV)",
        'nbins' : 25,
        'min' : 0,
        'max' : 10,
        'log' : True,
        },
    'cosTheta_bb':{
        'title' : "cosTheta(b,b) (GeV)",
        'nbins' : 10,
        'min' : 0,
        'max' : 1,
        'log' : True,
        },
    'min_DeltaR':{
        'title' : "min #DeltaR(jets) (GeV)",
        'nbins' : 8,
        'min' : 0,
        'max' : 8,
        'log' : True,
        },
    'max_DeltaR':{
        'title' : "max #DeltaR(jets) (GeV)",
        'nbins' : 20,
        'min' : 0,
        'max' : 20,
        'log' : True,
        },

    'pt_bjet': {
        'title' : "b-jet p_{T} (GeV)",
        'nbins' : 10,
        'min' : 0,
        'max' : 400,
        'log' : True,
    },
    'Jet1_pt': {
        'title' : "jet 1 p_{T} (GeV)",
        'nbins' : 15,
        'min' : 0,
        'max' : 600,
        'log' : True,
    },
    'Jet2_pt': {
        'title' : "jet 2 p_{T} (GeV)",
        'nbins' : 10,
        'min' : 0,
        'max' : 400,
        'log' : True,
    },
    'Jet3_pt': {
        'title' : "jet 3 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'Jet4_pt': {
        'title' : "jet 4 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'Jet5_pt': {
        'title' : "jet 5 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'Jet6_pt': {
        'title' : "jet 6 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'JetF_pt': {
        'title' : "jet forward p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'Jet1_csv': {
        'title' : "jet 1 CSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'Jet2_csv': {
        'title' : "jet 2 CSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'Jet3_csv': {
        'title' : "jet 3 CSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'Jet4_csv': {
        'title' : "jet 4 CSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'CosThetaStar': {
        'title' : "cos(#theta*)",
        'nbins' : 50,
        'min' : -1,
        'max' : 1,
        'log' : False,
    },
    'CosTheta1': {
        'title' : "cos(#theta_{1})",
        'nbins' : 50,
        'min' : -1,
        'max' : 1,
        'log' : False,
    },
    'ratio_jet1pt_HT': {
        'title' : "jet1 p_{T}/H_{T}",
        'nbins' : 50,
        'min' : -1,
        'max' : 1,
        'log' : False,
        'formula': "Jet1_pt/HT",
    },
}

