#! /usr/bin/env python

variable = {
    'nPV': {
        'title' : "number of primary vertices",
        'nbins' : 51,
        'min' : -0.5,
        'max' : 50.5,
        'log' : False,
    },
    'nElectrons': {
        'title' : "number of electrons",
        'nbins' : 5,
        'min' : -0.5,
        'max' : 4.5,
        'log' : True,
    },
    'nMuons': {
        'title' : "number of muons",
        'nbins' : 5,
        'min' : -0.5,
        'max' : 4.5,
        'log' : True,
    },
     'nTaus': {
        'title' : "number of #tau",
        'nbins' : 5,
        'min' : -0.5,
        'max' : 4.5,
        'log' : True,
    },
    'nJets': {
        'title' : "number of AK4 jets",
        'nbins' : 10,
        'min' : -0.5,
        'max' : 9.5,
        'log' : True,
    },
    'nForwardJets': {
        'title' : "number of forward AK4 jets",
        'nbins' : 10,
        'min' : -0.5,
        'max' : 9.5,
        'log' : True,
    },
    'nBJets': {
        'title' : "number of AK4 jets",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'log' : True,
    },
    'nBQuarks': {
        'title' : "number of AK4 jets",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'log' : True,
    },
   'nBTagJets': {
        'title' : "number of b-tagged AK4 jets",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'log' : True,
    },
    'MET_pt': {
        'title' : "#slash{E}_{T} (GeV)",
        'bins' : [250, 320, 400, 500, 650, 900, 1200, 1600, 2000],
        'nbins' : -1, #30,
        'min' : 250,
        'max' : 1450,
        'log' : True,
    },
    'MET_phi': {
        'title' : "fake-#slash{E}_{T} #phi",
        'nbins' : 36,
        'min' : -3.15,
        'max' : 3.15,
        'log' : False,
    },
    'MET_sign': {
        'title' : "#slash{E}_{T} (GeV)", #"#slash{E}_{T} significance",
        'bins' : [160, 200, 250, 320, 400, 500, 650, 900, 1200],
        'nbins' : -1, #30,
        'min' : 250,
        'max' : 1450,
        'log' : True,
    },
    'FakeMET_pt': {
        'title' : "Hadronic recoil (GeV)",
        'bins' : [250, 320, 400, 500, 650, 900, 1200, 1600, 2000],
        'nbins' : -1, #30,
        'min' : 250,
        'max' : 1450,
        'log' : True,
    },
    'HT': {
        'title' : "HT (GeV)",
        'nbins' : 20,
        'min' : 0,
        'max' : 2000.,
        'log' : True,
    },
    'ST': {
        'title' : "HT (GeV)",
        'nbins' : 20,
        'min' : 0,
        'max' : 2000.,
        'log' : True,
    },
    'MinDPhi': {
        'title' : "min #Delta #varphi (jet-#slash{E}_{T})",
        'nbins' : 28,
        'min' : 0,
        'max' : 3.15,
        'log' : True,
    },
    'MinDPhi12': {
        'title' : "min #Delta #varphi (jet_{1,2}-#slash{E}_{T})",
        'nbins' : 28,
        'min' : 0,
        'max' : 3.15,
        'log' : False,
    },
    'mZ': {
        'title' : "Z mass (GeV)",
        'nbins' : 60,
        'min' : 60,
        'max' : 120,
        'log' : False,
    },
    'mT': {
        'title' : "m_{T}^{W} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 240,
        'log' : False,
    },
    'mT2': {
        'title' : "m_{T2}^{W} (GeV)",
        'nbins' : 40,
        'min' : 80,
        'max' : 480,
        'log' : False,
    },
    'V_pt': {
        'title' : "Z p_{T} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 2000,
        'log' : True,
    },
    'Lepton1_pt': {
        'title' : "lepton 1 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'Lepton2_pt': {
        'title' : "lepton 2 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'Lepton1_pfIso': {
        'title' : "lepton 1 isolation (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 5,
        'log' : True,
    },
    'Lepton2_pfIso': {
        'title' : "lepton 2 isolation (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 5,
        'log' : True,
    },
    'Jet1_pt': {
        'title' : "jet 1 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'Jet2_pt': {
        'title' : "jet 2 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'Jet3_pt': {
        'title' : "jet 3 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'Jet4_pt': {
        'title' : "jet 4 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'JetF_pt': {
        'title' : "jet forward p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'log' : True,
    },
    'Jet1_csv': {
        'title' : "jet 1 CSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'Jet2_csv': {
        'title' : "jet 2 CSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'Jet3_csv': {
        'title' : "jet 3 CSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'Jet4_csv': {
        'title' : "jet 4 CSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'CosThetaStar': {
        'title' : "cos(#theta*)",
        'nbins' : 50,
        'min' : -1,
        'max' : 1,
        'log' : False,
    },
    'CosTheta1': {
        'title' : "cos(#theta_{1})",
        'nbins' : 50,
        'min' : -1,
        'max' : 1,
        'log' : False,
    },
}

